[package]
name = "http_demo"
version = "0.1.0"
authors = ["dermot"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rio = "0.9.4"
httparse = "1.3.4"
async-std = {version = "1.6.3", features = ["attributes"]}
